# Generated by Django 4.2.1 on 2023-06-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_accesorioscamion_accesoriosempleado_auditoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubierta',
            name='fechac',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cubierta',
            name='posicion',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cubierta',
            name='posicion2',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
