# Generated by Django 4.2.1 on 2023-06-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorioscamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Accesoriosempleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=12)),
                ('año', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentimiento', models.BooleanField(default=True)),
                ('entrada', models.DateField(auto_now_add=True)),
                ('salida', models.DateField(auto_now=True)),
                ('horasextras', models.CharField(max_length=1)),
                ('viaticos', models.CharField(max_length=1)),
                ('kmsalida', models.CharField(max_length=20)),
                ('kmllegada', models.CharField(max_length=20)),
                ('observaciones', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentorecivida', models.DateField(auto_now_add=True)),
                ('momentocumplida', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clientes')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.jornadas')),
            ],
        ),
        migrations.CreateModel(
            name='Servicecamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharealizacion', models.DateField(auto_now_add=True)),
                ('km', models.CharField(max_length=10)),
                ('kmproximo', models.CharField(max_length=10)),
                ('detalle', models.TextField(max_length=500)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
        migrations.CreateModel(
            name='Perfilempleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('empleado', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientocamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(max_length=300)),
                ('imagen', models.ImageField(upload_to='camion/')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
        migrations.AddField(
            model_name='jornadas',
            name='empleadop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado'),
        ),
        migrations.CreateModel(
            name='Habilitacionesempleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('vencimiento', models.DateField(auto_now=True)),
                ('empleadop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado')),
            ],
        ),
        migrations.CreateModel(
            name='Habilitacionescamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechavencimiento', models.DateTimeField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
        migrations.CreateModel(
            name='DetVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('observaciones', models.TextField(max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='visitas/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.productos')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.visitas')),
            ],
        ),
        migrations.CreateModel(
            name='Cubiertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('kmcolocacion', models.CharField(max_length=10)),
                ('kmrotacion', models.CharField(max_length=10)),
                ('kmrecambio', models.CharField(max_length=10)),
                ('fechacolocacion', models.DateField(auto_now_add=True)),
                ('posicion', models.CharField(max_length=2)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
        migrations.CreateModel(
            name='Checkcamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luces', models.BooleanField(default=True)),
                ('limpiaparabrizas', models.BooleanField(default=True)),
                ('frenos', models.BooleanField(default=True)),
                ('nivelFluidos', models.BooleanField(default=True)),
                ('Cubiertas', models.BooleanField(default=True)),
                ('plataforma', models.BooleanField(default=True)),
                ('extructura', models.BooleanField(default=True)),
                ('amarres', models.BooleanField(default=True)),
                ('accesorios', models.BooleanField(default=True)),
                ('observaciones', models.TextField(max_length=300)),
                ('imagen', models.ImageField(upload_to='camion/')),
                ('Jornadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.jornadas')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
                ('empleadop', models.ManyToManyField(to='project.perfilempleado')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorioentregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrega', models.DateField(auto_now=True)),
                ('empleadop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.accesoriosempleado')),
            ],
        ),
    ]
