# Generated by Django 4.2.1 on 2023-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_cubierta_fechac_cubierta_posicion_cubierta_posicion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitacionescamion',
            name='imagen1',
            field=models.ImageField(default='', upload_to='camion/'),
        ),
        migrations.AddField(
            model_name='habilitacionesempleado',
            name='imagen1',
            field=models.ImageField(default='', upload_to='empleado/'),
        ),
        migrations.AlterField(
            model_name='habilitacionesempleado',
            name='empleado',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='habilitacionesempleado',
            name='vencimiento',
            field=models.CharField(max_length=50),
        ),
    ]
