# Generated by Django 4.2.1 on 2023-06-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_jornadas_checkcamion_jornada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='empleadop',
        ),
        migrations.CreateModel(
            name='Capacitacione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.capacitacion')),
                ('empleadop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado')),
            ],
        ),
    ]
