# Generated by Django 4.2.1 on 2023-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_habilitacionescamion_imagen1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilempleado',
            old_name='cargo',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='capacitacione',
            name='capacitacion',
        ),
        migrations.RemoveField(
            model_name='capacitacione',
            name='realizada',
        ),
        migrations.AddField(
            model_name='capacitacione',
            name='duracion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitacione',
            name='fecha',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitacione',
            name='profesor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitacione',
            name='temas',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='observaciones',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='periodo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesorioentregado',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accesorioentregado',
            name='fechaentrega',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accesorioentregado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='capacitacione',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilempleado',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
    ]
