# Generated by Django 4.2.1 on 2023-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_cargo_perfilempleado_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkcamion',
            name='imagen',
            field=models.ImageField(default=False, upload_to='camion/'),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='imagen2',
            field=models.ImageField(default=False, upload_to='camion/'),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='kmsalida',
            field=models.CharField(default='', max_length=20),
        ),
    ]
