# Generated by Django 4.2.1 on 2023-06-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_jornada_checkcamion_jornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(max_length=300)),
                ('calificacion', models.CharField(max_length=200)),
                ('empleadop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.jornadas')),
            ],
        ),
    ]
