# Generated by Django 4.2.1 on 2023-06-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoriosempleado',
            name='precio',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
