# Generated by Django 4.2.1 on 2023-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_visitas_flujo_visitas_horas_visitas_litros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('diereccion', models.CharField(max_length=50)),
            ],
        ),
    ]
