# Generated by Django 4.2.1 on 2023-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_accesoriosempleado_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorioscamion',
            name='fechacompra',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='salida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='momentorecibida',
            field=models.DateField(),
        ),
    ]
