# Generated by Django 4.2.1 on 2023-06-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_accesorioscamion_fechacompra_alter_jornadas_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'ordering': ['nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
