# Generated by Django 4.2.1 on 2023-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_envases_opcion1_envases_opcion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envases',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
