# Generated by Django 4.2.1 on 2023-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_envases_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envases',
            name='opcion1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='envases',
            name='opcion2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
