# Generated by Django 4.2.1 on 2023-06-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_empleados_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
