# Generated by Django 4.2.1 on 2023-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_empleados_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientocamion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='codigo',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='posicion2',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='mantenimientocamion',
            name='imagen1',
            field=models.ImageField(null=True, upload_to='camion/'),
        ),
        migrations.AddField(
            model_name='mantenimientocamion',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='camion/'),
        ),
        migrations.AddField(
            model_name='servicecamion',
            name='imagen1',
            field=models.ImageField(null=True, upload_to='camion/'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='momentocumplida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='momentorecibida',
            field=models.DateTimeField(),
        ),
    ]
