# Generated by Django 4.2.1 on 2023-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_mantenimientocamion_imagen_cubiertas_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertas',
            name='posicion2',
            field=models.CharField(max_length=2),
        ),
    ]
