# Generated by Django 4.2.1 on 2023-06-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_checkcamion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadas',
            name='empleadop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado'),
        ),
    ]
