# Generated by Django 4.2.1 on 2023-06-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_capacitacione_empleadop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacione',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='jornadas',
            name='empleado',
        ),
        migrations.AddField(
            model_name='capacitacione',
            name='empleadop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornadas',
            name='empleadop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.perfilempleado'),
        ),
    ]
