# Generated by Django 4.2.1 on 2023-06-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_jornadas_empleadop_jornadas_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorioentregado',
            name='empleadop',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='empleadop',
        ),
        migrations.RemoveField(
            model_name='capacitacione',
            name='empleadop',
        ),
        migrations.RemoveField(
            model_name='habilitacionesempleado',
            name='empleadop',
        ),
        migrations.AddField(
            model_name='accesorioentregado',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empleados'),
        ),
        migrations.AddField(
            model_name='accesorioscamion',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empleados'),
        ),
        migrations.AddField(
            model_name='capacitacione',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empleados'),
        ),
        migrations.AddField(
            model_name='checkcamion',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empleados'),
        ),
        migrations.AddField(
            model_name='checkcamion',
            name='firma',
            field=models.ImageField(null=True, upload_to='camion/'),
        ),
        migrations.AddField(
            model_name='checkcamion',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='camion/'),
        ),
        migrations.AddField(
            model_name='habilitacionesempleado',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.empleados'),
        ),
        migrations.AddField(
            model_name='jornadas',
            name='camion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='observacion',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='accesorioentregado',
            name='nombre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.accesoriosempleado'),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='accesorios',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='amarres',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='camion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones'),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='cubiertas',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='estructura',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='frenos',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='jornada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.jornadas'),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='limpiaparabrizas',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='luces',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='nivelfluidos',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='plataforma',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cubiertas',
            name='camion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones'),
        ),
        migrations.AlterField(
            model_name='mantenimientocamion',
            name='camion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones'),
        ),
        migrations.AlterField(
            model_name='servicecamion',
            name='camion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.clientes'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='jornada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.jornadas'),
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechavencimiento', models.DateTimeField()),
                ('tema', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=10)),
                ('imagen1', models.ImageField(null=True, upload_to='camion/')),
                ('camion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechavencimiento', models.DateTimeField()),
                ('km', models.CharField(max_length=10)),
                ('Litros', models.CharField(max_length=10)),
                ('imagen1', models.ImageField(null=True, upload_to='camion/')),
                ('camion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.camiones')),
            ],
        ),
    ]
