# Generated by Django 4.2.1 on 2023-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_accesorioentregado_empleadop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combustible',
            name='fechavencimiento',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='fechavencimiento',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='checkcamion',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='combustible',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gastos',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesorioscamion',
            name='fechacompra',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cubiertas',
            name='fechacolocacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='habilitacionescamion',
            name='fechavencimiento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='camion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='entrada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='observaciones',
            field=models.TextField(default=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='salida',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimientocamion',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecamion',
            name='fecharealizacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='momentocumplida',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='momentorecibida',
            field=models.CharField(max_length=50),
        ),
    ]
