# Generated by Django 4.2.1 on 2023-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_combustible_fechavencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkcamion',
            name='camion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='camion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cubiertas',
            name='camion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='camion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='habilitacionescamion',
            name='camion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimientocamion',
            name='camion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecamion',
            name='camion',
            field=models.CharField(max_length=20),
        ),
    ]
