# Generated by Django 4.2.1 on 2023-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_visitas_direccion_remove_visitas_jornada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='checkcamion',
            name='jornada',
        ),
        migrations.AddField(
            model_name='visitas',
            name='direccion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkcamion',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jornadas',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
    ]
