# Generated by Django 4.2.1 on 2023-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_auditoria_jornada_remove_checkcamion_jornada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='momentocumplida',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='observacion',
            field=models.TextField(default=False, max_length=300),
        ),
    ]
