# Generated by Django 4.2.1 on 2023-06-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_visitas_momentocumplida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustible',
            name='importe',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
