# Generated by Django 4.2.1 on 2023-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_visitas_ciudad_visitas_imagen_alter_visitas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertas',
            name='fechacolocacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cubiertas',
            name='kmrecambio',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cubiertas',
            name='kmrotacion',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cubiertas',
            name='posicion2',
            field=models.CharField(default=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='imagen',
            field=models.ImageField(default=False, upload_to='visitas/'),
        ),
    ]
