# Generated by Django 4.2.1 on 2023-06-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_cubiertas_fechacolocacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='fechacolocacion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='kmcolocacion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='kmrecambio',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='kmrotacion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='posicion2',
        ),
    ]
