# Generated by Django 4.2.1 on 2023-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_cubiertas_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubiertas',
            name='codigo',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='kmcolocacion',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
