# Generated by Django 4.2.1 on 2023-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_cubiertas_codigo_cubiertas_kmcolocacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertas',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='kmrecambio',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='kmrotacion',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
