# Generated by Django 4.2.1 on 2023-06-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_cubiertas_fechacolocacion_cubiertas_posicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertas',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='posicion2',
        ),
    ]
