# Generated by Django 4.2.1 on 2023-06-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_remove_cubiertas_posicion_remove_cubiertas_posicion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertas',
            name='fechacolocacion',
        ),
    ]
