# Generated by Django 4.2.1 on 2023-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_remove_cubiertas_fechacolocacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubiertas',
            name='fechacolocacion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='posicion',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cubiertas',
            name='posicion2',
            field=models.CharField(default=True, max_length=2),
        ),
    ]
