# Generated by Django 4.2.1 on 2023-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_cubiertas_fechacolocacion_cubiertas_posicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertas',
            name='posicion',
            field=models.CharField(max_length=3),
        ),
    ]
