# Generated by Django 4.2.1 on 2023-06-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_alter_cubiertas_posicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cubiertas',
            old_name='fechacolocacion',
            new_name='fechac',
        ),
    ]
