# Generated by Django 4.2.1 on 2023-06-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_alter_cubiertas_posicion_alter_cubiertas_posicion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertas',
            name='fechac',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='kmcolocacion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='kmrecambio',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='kmrotacion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='cubiertas',
            name='posicion2',
        ),
    ]
