# Generated by Django 4.2.1 on 2023-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_remove_cubiertas_fechac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('kmcolocacion', models.CharField(max_length=10)),
                ('kmrotacion', models.CharField(default=True, max_length=10)),
                ('kmrecambio', models.CharField(default=True, max_length=10)),
                ('fechac', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=20)),
                ('posicion2', models.CharField(default=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cubiertas',
        ),
    ]
