# Generated by Django 4.2.1 on 2023-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_cubierta_delete_cubiertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubierta',
            name='posicion',
            field=models.CharField(max_length=22),
        ),
    ]
